### ISSUE TITLE
 Exception while invoking method 'serversession_set' Error: Did not check() all arguments during call to 'serversession_set'

### ISSUE THREAD

**Issue by almogdesign** [matteodem/meteor-server-session#8]
Getting the following error 

I20150905-22:30:32.082(3)? Exception while invoking method 'serversession_set' Error: Did not check() all arguments during call to 'serversession_set'
I20150905-22:30:32.084(3)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:357:1)
I20150905-22:30:32.084(3)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:112:1)
I20150905-22:30:32.084(3)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1614:1)
I20150905-22:30:32.084(3)?     at packages/ddp/livedata_server.js:648:1
I20150905-22:30:32.084(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150905-22:30:32.084(3)?     at packages/ddp/livedata_server.js:647:1
I20150905-22:30:32.084(3)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150905-22:30:32.084(3)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150905-22:30:32.084(3)?     at packages/ddp/livedata_server.js:546:1

**Comment by tewksbum** [comment]
+ 1

Exception while invoking method 'serversession_set' Error: Did not check() all arguments during call to 'serversession_set'
I20160128-10:18:23.657(-5)?     at [object Object]._.extend.throwUnlessAllArgumentsHaveBeenChecked (packages/check/match.js:411:1)
I20160128-10:18:23.657(-5)?     at Object.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
I20160128-10:18:23.657(-5)?     at maybeAuditArgumentChecks (livedata_server.js:1695:18)
I20160128-10:18:23.657(-5)?     at livedata_server.js:708:19
I20160128-10:18:23.658(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160128-10:18:23.658(-5)?     at livedata_server.js:706:40
I20160128-10:18:23.658(-5)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160128-10:18:23.658(-5)?     at livedata_server.js:704:46
I20160128-10:18:23.658(-5)?     at tryCallTwo (/Users/tewksbum/.meteor/packages/promise/.0.5.1.16ytvnd++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160128-10:18:23.659(-5)?     at doResolve (/Users/tewksbum/.meteor/packages/promise/.0.5.1.16ytvnd++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
